(source "melpa" "http://melpa.milkbox.net/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")

(depends-on "magit")
(depends-on "magit-filenotify")
(depends-on "auctex")
(depends-on "auto-async-byte-compile")
(depends-on "auto-complete")
(depends-on "auto-complete-clang")
(depends-on "cask")
(depends-on "color-theme")
(depends-on "color-theme-molokai")
(depends-on "color-theme-monokai")
(depends-on "color-theme-sanityinc-tomorrow")
(depends-on "color-theme-solarized")
(depends-on "dash")
(depends-on "dash-at-point")
(depends-on "epl")
(depends-on "exec-path-from-shell")
(depends-on "f")
(depends-on "fringe-helper")
(depends-on "git-gutter")
(depends-on "git-gutter-fringe")
(depends-on "minimap")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "popup")
(depends-on "powerline")
(depends-on "pyflakes")
(depends-on "pymacs")
(depends-on "python-mode")
(depends-on "python-pylint")
(depends-on "s")
(depends-on "tabbar")
(depends-on "yasnippet")
(depends-on "zenburn-theme")